# This makefile was auto-generated by Quickstart. You are free to modify it as you please.
# To find out more about Make, visit https://www.gnu.org/software/make/

build:
	bash build.sh

lint:
	npx eslint "*/**/*.ts"

lint-fix:
	npx eslint "*/**/*.ts" --fix
